Repository owncloud/owncloud-sdk, pull requests merged in 2019-08, with the labels that each got.

#303 Return proper path for oc.publicFiles.list
  src/helperFunctions.js
  src/publicLinkAccess.js
  tests/publicLinkTest.js
  yarn.lock
Labels: 3 - To Review

#304 oc.files.getFileUrl2 added + oc.publicFiles.getFileUrl fixed when pat…
  src/fileManagement.js
  src/publicLinkAccess.js
  tests/filesTest.js
  tests/publicLinkTest.js
Labels: 3 - To Review

#306 Extend share file with link
  src/shareManagement.js
Labels: 3 - To Review, enhancement

#308 Allow write operations on public-files
  src/publicLinkAccess.js
  src/shareManagement.js
  tests/publicLinkTest.js
  tests/sharingTest.js
  tests/unauthenticated/sharingTest.js
  tests/unauthorized/sharingTest.js
  yarn.lock
Labels: 3 - To Review

#310 Add oc.publicFiles.move and oc.publicFiles.copy
  src/publicLinkAccess.js
  tests/publicLinkTest.js
  yarn.lock
Labels: 3 - To Review

#309 Expand updateShare and shareFileWithLink
  src/shareManagement.js
Labels: 2 - Developing

#314 Convert drone.yml for drone 1
  .drone.yml
Labels: 3 - To Review

#317 no need to uft8 encode
  .drone.yml
  src/shareInfo.js
  src/shareManagement.js
  tests/sharingTest.js
  yarn.lock
Labels: 3 - To Review

#318 updateShare accepts empty password and expireDate
  src/shareManagement.js
Labels: bug

#315 Bugfix/configurable request headers
  src/helperFunctions.js
  src/owncloud.js
  yarn.lock
Labels: 3 - To Review

#331 Update dependencies 20190822
  yarn.lock
Labels: 3 - To Review

#330 Feature/share permissions via attributes
  src/helperFunctions.js
  src/shareManagement.js
  tests/sharingWithAttributesTest.js
Labels: 3 - To Review
