Repository owncloud/owncloud-sdk, pull requests merged in 2020-09, with the labels that each got.

#543 tests with pact.io
  .drone.yml
  .gitignore
  codecov.yml
  karma.conf.js
  package.json
  tests/appsTest.js
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/karma.js
  tests/loginTest.js
  tests/requestsOcsTest.js
  yarn.lock
Labels: QA-team

#552 apps tests
  tests/appsTest.js
  tests/karma.js
Labels: QA-team

#556 capabilities tests to pact.io
  tests/capabilitiesTest.js
  tests/karma.js
Labels: QA-team

#555 convert group tests to pact.io
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/groupTest.js
  tests/karma.js
Labels: QA-team

#563 convert some of the user tests to pact.io
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/karma.js
  tests/userTest.js
Labels: QA-team

#559 convert unautorized capabilities tests to pact.io
  tests/karma.js
  tests/unauthorized/capabilitiesTest.js
  tests/unauthorized/groupTest.js
Labels: QA-team

#564 Convert unauthorized sharing tests to pact.io
  .gitignore
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/karma.js
  tests/unauthorized/sharingTest.js
Labels: 3 - To Review, QA-team

#567 convert some of theunauthorized userTest to pact.io
  tests/karma.js
  tests/unauthorized/userTest.js
Labels: 3 - To Review, QA-team

#571 [Tests-Only] Replace 'not existing' with non-existent'
  tests/appsTest.js
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/filesTest.js
  tests/groupTest.js
  tests/karma.js
  tests/loginTest.js
  tests/sharingTest.js
  tests/unauthenticated/sharingTest.js
  tests/unauthenticated/userTest.js
  tests/unauthorized/sharingTest.js
  tests/unauthorized/userTest.js
  tests/userTest.js
Labels: 3 - To Review

#568 [Tests-Only]Convert remaining user tests to pact.io
  tests/karma.js
  tests/userTest.js
Labels: 3 - To Review

#573 [Tests-Only]Convert shareRecipient test to pact.io
  tests/karma.js
  tests/shareRecipientTest.js
Labels: 3 - To Review, QA-team

#575 [Tests-Only]Convert sharing with Attributes test to pact.io
  tests/karma.js
  tests/sharingWithAttributesTest.js
Labels: 3 - To Review, QA-team

#579 update @pact-foundation/pact-web
  yarn.lock
Labels: QA-team

#554 convert MKCOL tests to pact.io
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/filesTest.js
  tests/karma.js
Labels: QA-team

#557 convert public link tests to pact.io
  .gitignore
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/karma.js
  tests/publicLinkTest.js
Labels: QA-team

#577 [Tests-Only] Convert sharing test to pact.io
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/karma.js
  tests/sharingTest.js
Labels: 2 - Developing

#583 refactor pact.io tests to attach interactions to the tests
  tests/appsTest.js
  tests/capabilitiesTest.js
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/groupTest.js
  tests/karma.js
  tests/loginTest.js
  tests/pactHelper.js
  tests/publicLinkTest.js
  tests/requestsOcsTest.js
  tests/shareRecipientTest.js
  tests/sharingTest.js
  tests/sharingWithAttributesTest.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/capabilitiesTest.js
  tests/unauthorized/filesTest.js
  tests/unauthorized/groupTest.js
  tests/unauthorized/sharingTest.js
  tests/unauthorized/userTest.js
  tests/userTest.js
Labels: QA-team

#585 [Tests-Only] Refactor PactHelper
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/pactHelper.js
Labels: QA-team
