Repository owncloud/owncloud-sdk, pull requests merged in 2020-10, with the labels that each got.

#582 Convert unauthorized filesTest to pact.io
  tests/pactHelper.js
  tests/unauthorized/filesTest.js
Labels: QA-team

#590 [Tests-Only] Add interactions for the tests in sharing tests
  tests/pactHelper.js
  tests/sharingTest.js
Labels: QA-team

#593 Refactore unauthorized files test to include interactions inside test file
  tests/pactHelper.js
  tests/unauthorized/appsTest.js
Labels: QA-team

#596 [Tests-Only] Convert signed url integration tests to pact.io
  tests/pactHelper.js
  tests/signedUrlIntegrationTest.js
Labels: QA-team

#597 Refactored unauthorized sharing test
  tests/pactHelper.js
  tests/unauthorized/sharingTest.js
Labels: QA-team

#595 Refactored unauthorized group test
  tests/pactHelper.js
  tests/unauthorized/groupTest.js
Labels: QA-team

#591 [Tests-Only] Convert fileTrashTest.js to pact.io
  tests/config/config.drone.json
  tests/fileTrashTest.js
  tests/pactHelper.js
Labels: QA-team

#598 [Tests-Only] Interactions for user test added inside user test file
  tests/pactHelper.js
  tests/userTest.js
Labels: QA-team

#600 [Tests-Only] Interactions for group test added inside groupTest file
  tests/groupTest.js
  tests/pactHelper.js
Labels: QA-team

#602 [Tests-Only] Refactor sharing with attributes test
  tests/pactHelper.js
  tests/sharingWithAttributesTest.js
Labels: 3 - To Review, Hacktoberfest, QA-team

#606 [Tests-Only] Refactor capabilities test
  tests/capabilitiesTest.js
  tests/pactHelper.js
Labels: 3 - To Review, Hacktoberfest, QA-team

#604 [Tests-Only] Interactions for share Recipient test added into shareRecipient file
  tests/pactHelper.js
  tests/shareRecipientTest.js
Labels: 3 - To Review, QA-team

#603 [Tests-Only] Interactions for apps test added into apps test file
  tests/appsTest.js
  tests/pactHelper.js
Labels: 3 - To Review, QA-team

#601 [Tests-Only] Refactor fileVersionTest to use pact.io
  tests/fileVersionTest.js
  tests/pactHelper.js
Labels: 3 - To Review, QA-team

#612 Refactor unauthorized user tests file
  tests/pactHelper.js
  tests/unauthorized/userTest.js
Labels: QA-team
