Repository owncloud/owncloud-sdk, pull requests merged in 2021-03, with the labels that each got.

#737 [tests-only] Adjust pact interaction for publicLinkTest
  tests/helpers/sharingHelper.js
  tests/pactHelper.js
  tests/providerTest.js
  tests/publicLinkTest.js
Labels: 3 - To Review, QA:team

#748 [tests-only] Consistent interaction names
  tests/appsTest.js
  tests/capabilitiesTest.js
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/groupTest.js
  tests/pactHelper.js
  tests/publicLinkTest.js
  tests/requestsOcsTest.js
  tests/shareRecipientTest.js
  tests/sharingTest.js
  tests/sharingWithAttributesTest.js
  tests/signedUrlIntegrationTest.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/filesTest.js
  tests/unauthorized/groupTest.js
  tests/unauthorized/sharingTest.js
  tests/unauthorized/userTest.js
  tests/userTest.js
Labels: QA:team

#754 [tests-only] Do not set skeleton directory in CI
  .drone.star
Labels: QA:team

#732 [Tests-Only] Adjust pact interactions for provider tests for signedUrlIntegration
  tests/providerTest.js
  tests/signedUrlIntegrationTest.js
  tests/webdavHelper.js
Labels: 3 - To Review

#730 [tests-only] Adjust pact interactions for sharingWithAttributesTest
  tests/pactHelper.js
  tests/sharingTest.js
  tests/sharingWithAttributesTest.js
Labels: 3 - To Review, QA:team

#762 [Tests-Only] Remove use of promise from sync functions
  tests/providerTest.js
Labels: QA:team

#760 [tests-only] Adjust groupTest interactions for oCIS server
  tests/groupTest.js
Labels: QA:team

#761 [tests-only] Adjust loginTest interactions for oCIS server
  tests/pactHelper.js
Labels: QA:team

#753 [tests-only] Adjust userTest interactions for oCIS
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/pactHelper.js
  tests/userTest.js
Labels: QA:team

#768 [tests-only] Adjust shareRecipientTest and sharingWithAttributesTest interactions for oCIS
  tests/shareRecipientTest.js
  tests/sharingWithAttributesTest.js
Labels: QA:team

#766 [tests-only] Adjust requestOcsTest interactions for oCIS server
  tests/pactHelper.js
  tests/requestsOcsTest.js
Labels: QA:team

#770 [Tests-Only] Refactor backendHost and pact port config for pact tests
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/loginTest.js
  tests/pactHelper.js
  tests/publicLinkTest.js
  tests/signedUrlTest.js
  tests/unauthenticated/appsTest.js
  tests/unauthenticated/capabilitiesTest.js
  tests/unauthenticated/filesTest.js
  tests/unauthenticated/groupTest.js
  tests/unauthenticated/sharingTest.js
  tests/unauthenticated/userTest.js
Labels: 3 - To Review, QA:team

#728 [tests-only] Adjust pact interaction of sharingTest
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/helpers/providerStateHelper.js
  tests/helpers/sharingHelper.js
  tests/pactHelper.js
  tests/sharingTest.js
Labels: QA:team

#771 [Docs-Only] Document how to run pact tests
  README.md
Labels: QA:team

#774 add trailing slash for backendHost in example config
  tests/config/config.sample.json
Labels: QA:team

#773 update pact-js to 10.0.0-beta.33
  package.json
Labels: QA:team

#772 [tests-only] Adjust sharingTest interactions for oCIS server
  tests/sharingTest.js
Labels: QA:team

#769 [tests-only] Adjust fileTest interaction for oCIS
  tests/filesTest.js
  tests/pactHelper.js
Labels: QA:team

#779 [tests-only] Adjust unauthorized tests for ocis server
  tests/pactHelper.js
  tests/unauthorized/groupTest.js
  tests/unauthorized/sharingTest.js
  tests/unauthorized/userTest.js
Labels: QA:team

#778 [tests-only] Fix trailing '/' of the provider server url and check '/' at the beginning of requests in tests
  .drone.star
  tests/filesTest.js
  tests/helpers/sharingHelper.js
  tests/pactHelper.js
  tests/providerTest.js
  tests/webdavHelper.js
Labels: QA:team

#735 replace owncloud/davclient.js with webdav
  jest.init.js
  package.json
  src/dav.js
  src/fileManagement.js
  src/fileVersionManagement.js
  src/filesTrash.js
  src/helperFunctions.js
  src/publicLinkAccess.js
  src/systemTags.js
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/helpers/sharingHelper.js
  tests/pactHelper.js
  tests/parseClarkNotationTest.js
  tests/parseMultiStatusTest.js
  tests/providerTest.js
  tests/publicLinkTest.js
  tests/unauthorized/filesTest.js
  yarn.lock
Labels: QA:team

#781 [tests-only]Refactor backendHost and pactMockPort to get complete URL
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/loginTest.js
  tests/pactHelper.js
  tests/publicLinkTest.js
  tests/signedUrlTest.js
  tests/unauthenticated/appsTest.js
  tests/unauthenticated/capabilitiesTest.js
  tests/unauthenticated/filesTest.js
  tests/unauthenticated/groupTest.js
  tests/unauthenticated/sharingTest.js
  tests/unauthenticated/userTest.js
Labels: 3 - To Review, QA:team

#782 [Tests-Only] adjust pact interactions for unauthorized tests
  tests/unauthorized/filesTest.js
Labels: QA:team

#783 split provider tests into multiple pacts to be able to verify some interactions
  .drone.star
  jest.config.js
  jest.setup.js
  package.json
  tests/appsTest.js
  tests/capabilitiesTest.js
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/groupTest.js
  tests/loginTest.js
  tests/pactHelper.js
  tests/providerTest.js
  tests/publicLinkTest.js
  tests/requestsOcsTest.js
  tests/shareRecipientTest.js
  tests/sharingTest.js
  tests/sharingWithAttributesTest.js
  tests/signedUrlIntegrationTest.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/capabilitiesTest.js
  tests/unauthorized/filesTest.js
  tests/unauthorized/groupTest.js
  tests/unauthorized/sharingTest.js
  tests/unauthorized/userTest.js
  tests/userTest.js
Labels: QA:team

#792 [Tests-only] Refactor "filter by tag" test from fileTest.js
  tests/filesTest.js
Labels: QA:team

#798 [Tests-Only] adjust pact interactions for fileTrash and fileVersion tests
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/providerTest.js
  tests/webdavHelper.js
Labels: QA:team

#787 [tests-only] Make sharing and providerState helper functions modular/flexible
  tests/helpers/providerStateHelper.js
  tests/helpers/sharingHelper.js
  tests/providerTest.js
  tests/publicLinkTest.js
  tests/sharingTest.js
Labels: QA:team
