Repository owncloud/owncloud-sdk, pull requests merged in 2021-01, with the labels that each got.

#642 small drone fixes
  .drone.star
Labels: 3 - To Review, QA-team

#640 [Tests-Only] split interactions and verify them
  tests/pactHelper.js
  tests/requestsOcsTest.js
Labels: 3 - To Review, QA-team

#649 [Tests-Only] Refactor sharing with attributes test and verify it
  tests/sharingWithAttributesTest.js
Labels: 3 - To Review, QA-team

#652 [Tests-Only] Verify share recipient test
  tests/shareRecipientTest.js
Labels: 3 - To Review, QA-team

#638 [Tests-Only]Refactor the capabilities test file to use provider verify
  tests/capabilitiesTest.js
  tests/pactHelper.js
  tests/requestsOcsTest.js
Labels: 3 - To Review, QA-team

#651 [Tests-Only] refactor pactHelper setGeneralInteractions functions
  tests/pactHelper.js
Labels: QA-team

#654 [Tests-Only] Verify unauthorized tests
  tests/pactHelper.js
  tests/signedUrlIntegrationTest.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/capabilitiesTest.js
  tests/unauthorized/filesTest.js
  tests/unauthorized/groupTest.js
  tests/unauthorized/sharingTest.js
  tests/unauthorized/userTest.js
Labels: 3 - To Review, QA-team

#655 [Tests-Only] Verify user test
  tests/pactHelper.js
  tests/userTest.js
Labels: 3 - To Review, QA-team

#656 [Tests-Only] add provider.verify() on appTest, fileTrashTest and filesTest
  tests/appsTest.js
  tests/fileTrashTest.js
  tests/filesTest.js
  tests/pactHelper.js
Labels: 3 - To Review, QA-team

#659 [Tests-Only] Verify public link tests
  tests/publicLinkTest.js
Labels: 3 - To Review, QA-team

#661 [Tests-Only] add provider.verify() on file version test
  tests/fileVersionTest.js
Labels: QA-team

#660 [Tests-Only]Test sharing refactor
  tests/sharingTest.js
Labels: 3 - To Review, QA-team

#671 [Tests-Only] remove provider.verify() call
  tests/pactHelper.js
  tests/sharingTest.js
Labels: 3 - To Review, QA-team

#672 [Tests-Only] refactor and cleanup fileVersionTest and publicLinkTest
  tests/fileVersionTest.js
  tests/publicLinkTest.js
Labels: QA-team

#669 [Tests-Only] refactor and cleanup filesTest
  tests/filesTest.js
Labels: 3 - To Review, QA-team

#637 move tests to jest & pactV3 (capabilitiesTest.js)
  .drone.star
  jest.config.js
  jest.init.js
  karma.conf.js
  package-lock.json
  package.json
  src/helperFunctions.js
  tests/capabilitiesTest.js
  tests/karma.js
  tests/pactHelper.js
  yarn.lock
Labels: QA-team

#673 convert groupTests to jest and pactV3
  jest.config.js
  tests/groupTest.js
  tests/pactHelper.js
Labels: QA-team

#674 [Tests-Only] move appsTest to jest
  .gitignore
  jest.config.js
  tests/appsTest.js
Labels: 3 - To Review, QA-team

#682 [Tests-Only] move userTest.js to jest and pactV3
  jest.config.js
  tests/pactHelper.js
  tests/userTest.js
Labels: 3 - To Review

#687 [Tests-Only] Move unauthenticated tests to jest
  jest.config.js
  src/helperFunctions.js
  tests/unauthenticated/filesTest.js
Labels: 3 - To Review

#691 [Tests-Only] move unauthorized appsTest to jest
  jest.config.js
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/pactHelper.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/capabilitiesTest.js
Labels: 3 - To Review

#693 [Tests-Only] move LoginTest to jest and pactv3
  jest.config.js
  tests/loginTest.js
  tests/pactHelper.js
Labels: 3 - To Review

#688 [Tests-Only] move signedUrl, sharingWithAttributres and shareRecipientTest to jest and pactV3
  jest.config.js
  tests/XmlParserTest.js
  tests/pactHelper.js
  tests/shareRecipientTest.js
  tests/sharingWithAttributesTest.js
  tests/signedUrlIntegrationTest.js
  tests/signedUrlTest.js
Labels: 3 - To Review

#697 [Tests-Only] Move unauthorized/sharingTest to jest and pactV3
  jest.config.js
  tests/unauthorized/sharingTest.js
Labels: 3 - To Review

#694 [Tests-Only] Convert unauthorized userTest to jest
  jest.config.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/userTest.js
Labels: 3 - To Review, QA-team

#698 [Tests-Only]refactor userTest
  tests/unauthorized/userTest.js
Labels: 3 - To Review, QA-team

#695 [Tests-Only] move requestOcsTest and shareRecipientTest to jest and pactv3
  jest.config.js
  tests/pactHelper.js
  tests/requestsOcsTest.js
Labels: 3 - To Review

#699 [Tests-Only] move sharing test to pactV3 and jest
  jest.config.js
  jest.init.js
  package.json
  tests/pactHelper.js
  tests/sharingTest.js
  yarn.lock
Labels: 3 - To Review

#704 [tests-only] fix tests that use x-www-form-urlencoded body
  package.json
  tests/pactHelper.js
  tests/sharingTest.js
  tests/sharingWithAttributesTest.js
  tests/userTest.js
  yarn.lock
Labels: QA-team

#702 [Tests-Only] move publicLinkTest to pactv3 and jest
  jest.config.js
  tests/pactHelper.js
  tests/publicLinkTest.js
Labels: 3 - To Review, QA-team

#700 [Tests-Only] move fileTrashTest to pactv3 and jest
  jest.config.js
  tests/fileTrashTest.js
Labels: 3 - To Review, QA-team

#701 [Tests-Only] move fileVersionTest to pactv3 and jest
  jest.config.js
  tests/fileVersionTest.js
Labels: 3 - To Review

#707 [tests-only] fix comments about issues in txt response
  tests/signedUrlIntegrationTest.js
Labels: QA-team

#696 [Tests-Only] move FilesTest to pactV3 and jest
  jest.config.js
  src/helperFunctions.js
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/filesTest.js
  tests/pactHelper.js
Labels: 3 - To Review
