Repository owncloud/owncloud-sdk, pull requests merged in 2021-02, with the labels that each got.

#662 provider tests run in drone with oc10
  .drone.star
  jest.config.js
  package.json
  tests/appsTest.js
  tests/capabilitiesTest.js
  tests/groupTest.js
  tests/pactHelper.js
  tests/providerTest.js
  yarn.lock
Labels: QA-team

#711 update pact.js & fix tests that were skipped because of a pact bug
  package.json
  tests/filesTest.js
  tests/pactHelper.js
  tests/signedUrlIntegrationTest.js
  yarn.lock
Labels: QA-team

#716 [tests-only] some fixes to make more files tests pass in the provider
  tests/filesTest.js
  tests/pactHelper.js
  tests/providerTest.js
  tests/webdavHelper.js
Labels: QA-team

#718 [tests-only] code cleanup
  .drone.star
  tests/appsTest.js
  tests/capabilitiesTest.js
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/groupTest.js
  tests/loginTest.js
  tests/pactHelper.js
  tests/providerTest.js
  tests/publicLinkTest.js
  tests/requestsOcsTest.js
  tests/shareRecipientTest.js
  tests/sharingTest.js
  tests/sharingWithAttributesTest.js
  tests/signedUrlIntegrationTest.js
  tests/signedUrlTest.js
  tests/unauthenticated/userTest.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/capabilitiesTest.js
  tests/unauthorized/filesTest.js
  tests/unauthorized/groupTest.js
  tests/unauthorized/sharingTest.js
  tests/unauthorized/userTest.js
  tests/userTest.js
Labels: QA-team

#721 update pact-js to 10.0.0-beta.30
  package.json
  yarn.lock
Labels: QA-team

#720 adjust create/delete folder tests to pass on oc10 provider
  .drone.star
  tests/appsTest.js
  tests/capabilitiesTest.js
  tests/fileTrashTest.js
  tests/fileVersionTest.js
  tests/filesTest.js
  tests/groupTest.js
  tests/pactHelper.js
  tests/providerTest.js
  tests/publicLinkTest.js
  tests/requestsOcsTest.js
  tests/shareRecipientTest.js
  tests/sharingTest.js
  tests/sharingWithAttributesTest.js
  tests/signedUrlIntegrationTest.js
  tests/userTest.js
  tests/webdavHelper.js
Labels: QA-team

#725 refactor files tests to work on oc10 provider
  tests/filesTest.js
  tests/pactHelper.js
  tests/providerTest.js
Labels: QA-team

#726 revert hacks that were introduced because of char encoding bug in pact
  package.json
  tests/pactHelper.js
  tests/sharingTest.js
  yarn.lock
Labels: QA-team

#729 run all tests
  jest.config.js
Labels: QA:team

#731 [tests-only] Adjust pact interactions for requestsOcsTest
  tests/providerTest.js
  tests/requestsOcsTest.js
Labels: 3 - To Review, QA:team

#727 [Tests-Only] Adjust pact interactions for provider tests for shareRecepient
  src/shareManagement.js
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/shareRecipientTest.js
Labels: 3 - To Review

#738 [Tests-Only]Adjust username and password in shareRecipient test
  tests/config/config.drone.json
  tests/config/config.sample.json
  tests/shareRecipientTest.js
Labels: 3 - To Review

#736 modify files versions tests to pass with oC10 provider
  package.json
  tests/fileVersionTest.js
  tests/providerTest.js
  tests/webdavHelper.js
  yarn.lock
Labels: QA:team

#739 Improve docs regarding share attributes
  src/shareManagement.js
Labels: 3 - To Review

#740 run provider tests in ocis
  .drone.env
  .drone.star
  tests/providerTest.js
Labels: QA:team

#741 remove pact log step from drone
  .drone.star
Labels: QA:team

#742 accept application/xml content-type where oc10 sends text/xml
  tests/pactHelper.js
  tests/unauthorized/appsTest.js
  tests/unauthorized/groupTest.js
  tests/userTest.js
Labels: QA:team

#743 use consumerVersionTags option instead of consumerVersionSelectors
  tests/providerTest.js
Labels: QA:team

#746 [tests-only ] Fix content-type in tests
  tests/pactHelper.js
Labels: QA:team
